// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./components/signup.tsx": {
    id: "components/signup";
    page: "/signup";
  };
};